resultado = int(input('Escreva um valor: '))
money = float(input('R$'))
nota1 = int(input('Primeira nota: '))
nota2 = int(input('Segunda nota: '))
metros = int(input('Metros: '))
raizq = resultado **(1/2)
print('O sucessor de {} é: {}'.format(resultado, resultado +1))
print('O antecessor de {} é: {}'.format(resultado, resultado -1))
print('O dobro de {} é: {}'.format(resultado, resultado *2))
print('O triplo de {} é: {}'.format(resultado, resultado *3))
print('A raiz quadrada de {} é: {:.2f}'.format(resultado, raizq))
print('A média das notas é: {}'.format((nota1 + nota2)/2))
print('US${:.2f}'.format(money / 3.27))
print('{} metros tem {} centímetros e {} milímetros.'.format(metros, metros*100, metros*1000))
print('2 x {} = {}'.format(resultado, resultado*2))
print('3 x {} = {}'.format(resultado, resultado*3))
print('4 x {} = {}'.format(resultado, resultado*4))
print('5 x {} = {}'.format(resultado, resultado*5))
print('6 x {} = {}'.format(resultado, resultado*6))
print('7 x {} = {}'.format(resultado, resultado*7))
print('8 x {} = {}'.format(resultado, resultado*8))
print('9 x {} = {}'.format(resultado, resultado*9))
print('10 x {} = {}'.format(resultado, resultado*10))